//
// Created by Max on 07.03.2022.
//

#ifndef CHESSPROJECT_SOURCE_LOGIC_HEADERS_MOVES_INVALIDMOVE_H_
#define CHESSPROJECT_SOURCE_LOGIC_HEADERS_MOVES_INVALIDMOVE_H_

#endif //CHESSPROJECT_SOURCE_LOGIC_HEADERS_MOVES_INVALIDMOVE_H_
