//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_MENUBUTTON_H_
#define CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_MENUBUTTON_H_

class MenuButton {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_MENUBUTTON_H_
