//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_NEWGAMECLASSICMODEBUTTON_H_
#define CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_NEWGAMECLASSICMODEBUTTON_H_

class NewGameClassicModeButton {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_NEWGAMECLASSICMODEBUTTON_H_
