//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_SURRENDERBUTTON_H_
#define CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_SURRENDERBUTTON_H_

class SurrenderButton {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTONS_SURRENDERBUTTON_H_
