//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_INTERFACE_H_
#define CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_INTERFACE_H_

class InterFace {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_INTERFACE_H_
