//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_WINDOW_H_
#define CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_WINDOW_H_

class Window {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_WINDOW_H_
