//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_LOGIC_ACTIONS_ACTION_H_
#define CHESSPROJECT_SOURCE_INTERFACE_LOGIC_ACTIONS_ACTION_H_

class Action {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_LOGIC_ACTIONS_ACTION_H_
