//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_MENUWINDOW_H_
#define CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_MENUWINDOW_H_

class MenuWindow {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_INTERFACE_MENUWINDOW_H_
