
#ifndef CHESSPROJECT_SOURCE_INTERFACE_HEADERS_WINDOWS_MENUWINDOW_H_
#define CHESSPROJECT_SOURCE_INTERFACE_HEADERS_WINDOWS_MENUWINDOW_H_

class MenuWindow {
 public:
  MenuWindow();

 private:

};

#endif
