
#ifndef CHESSPROJECT_SOURCE_INTERFACE_CONSOLE_INTERFACE_HEADERS_WINDOWS_WINDOWS_H_
#define CHESSPROJECT_SOURCE_INTERFACE_CONSOLE_INTERFACE_HEADERS_WINDOWS_WINDOWS_H_

#include "Window.h"
#include "GameWindow.h"
#include "MenuWindow.h"

#endif
