
#ifndef CHESSPROJECT_SOURCE_MAIN_HEADERS_SCRIPTS_SCRIPTS_H_
#define CHESSPROJECT_SOURCE_MAIN_HEADERS_SCRIPTS_SCRIPTS_H_

#include "Game.h"
#include "Menu.h"

#endif //CHESSPROJECT_SOURCE_MAIN_HEADERS_SCRIPTS_SCRIPTS_H_
