
#ifndef CHESSPROJECT_SOURCE_MAIN_HEADERS_SCRIPTS_SCRIPTS_H_
#define CHESSPROJECT_SOURCE_MAIN_HEADERS_SCRIPTS_SCRIPTS_H_

#include "Script.h"
#include "GameScript.h"
#include "MenuScript.h"
#include "ExitScript.h"

#endif //CHESSPROJECT_SOURCE_MAIN_HEADERS_SCRIPTS_SCRIPTS_H_
