//
// Created by Георгий Кузнецов on 10.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_LOGIC_HEADERS_ERRORTYPE_H_
#define CHESSPROJECT_SOURCE_LOGIC_HEADERS_ERRORTYPE_H_
enum class ErrorTypes: int{
  EMPTY,
  CANCEL_MOVE,
  INVALID_MOVE,
  REJECT_MOVE
};
#endif //CHESSPROJECT_SOURCE_LOGIC_HEADERS_ERRORTYPE_H_
