
#ifndef CHESSPROJECT_SOURCE_INTERFACE_HEADERS_LOGIC_PART_H_
#define CHESSPROJECT_SOURCE_INTERFACE_HEADERS_LOGIC_PART_H_

#include "../../logic/headers/logic.h"

#endif //CHESSPROJECT_SOURCE_INTERFACE_HEADERS_LOGIC_PART_H_
