//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_LOGIC_WRAPPERS_PIECEWRAPPER_H_
#define CHESSPROJECT_SOURCE_INTERFACE_LOGIC_WRAPPERS_PIECEWRAPPER_H_

class PieceWrapper {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_LOGIC_WRAPPERS_PIECEWRAPPER_H_
