//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_LOGIC_WRAPPERS_POSITIONWRAPPER_H_
#define CHESSPROJECT_SOURCE_INTERFACE_LOGIC_WRAPPERS_POSITIONWRAPPER_H_

class PositionWrapper {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_LOGIC_WRAPPERS_POSITIONWRAPPER_H_
