//
// Created by Георгий Кузнецов on 09.04.2022.
//

#ifndef CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTON_H_
#define CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTON_H_

class Button {

};

#endif //CHESSPROJECT_SOURCE_INTERFACE_BUTTON_BUTTON_H_
